/*
  LV2 Darkglass Custom Styling Extension
  Copyright 2026 Filipe Coelho <falktx@darkglass.com>

  Permission to use, copy, modify, and/or distribute this software for any
  purpose with or without fee is hereby granted, provided that the above
  copyright notice and this permission notice appear in all copies.

  THIS SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

/**
   @file lv2_darkglass_custom_styling.h
   C header for the LV2 Darkglass Custom Styling extension <http://www.darkglass.com/lv2/ns/lv2ext/custom-styling>.
*/

#ifndef LV2_DARKGLASS_CUSTOM_STYLING_H
#define LV2_DARKGLASS_CUSTOM_STYLING_H

#define LV2_DARKGLASS_CUSTOM_STYLING_URI    "http://www.darkglass.com/lv2/ns/lv2ext/custom-styling"
#define LV2_DARKGLASS_CUSTOM_STYLING_PREFIX LV2_DARKGLASS_CUSTOM_STYLING_URI "#"

#define LV2_DARKGLASS_CUSTOM_STYLING__alignBottomLeft       LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignBottomLeft"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignBottomMid        LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignBottomMid"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignBottomRight      LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignBottomRight"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignCenter           LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignCenter"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignLeftMid          LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignLeftMid"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignRightMid         LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignRightMid"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignTopLeft          LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignTopLeft"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignTopMid           LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignTopMid"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignTopRight         LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignTopRight"
#define LV2_DARKGLASS_CUSTOM_STYLING__alignment             LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "alignment"
#define LV2_DARKGLASS_CUSTOM_STYLING__back                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "back"
#define LV2_DARKGLASS_CUSTOM_STYLING__background            LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "background"
#define LV2_DARKGLASS_CUSTOM_STYLING__backgroundScenes      LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "backgroundScenes"
#define LV2_DARKGLASS_CUSTOM_STYLING__blockImage            LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "blockImage"
#define LV2_DARKGLASS_CUSTOM_STYLING__blockName             LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "blockName"
#define LV2_DARKGLASS_CUSTOM_STYLING__blockSettings         LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "blockSettings"
#define LV2_DARKGLASS_CUSTOM_STYLING__blocked               LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "blocked"
#define LV2_DARKGLASS_CUSTOM_STYLING__bypass                LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "bypass"
#define LV2_DARKGLASS_CUSTOM_STYLING__close                 LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "close"
#define LV2_DARKGLASS_CUSTOM_STYLING__control               LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "control"
#define LV2_DARKGLASS_CUSTOM_STYLING__font                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "font"
#define LV2_DARKGLASS_CUSTOM_STYLING__height                LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "height"
#define LV2_DARKGLASS_CUSTOM_STYLING__inUse                 LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "inUse"
#define LV2_DARKGLASS_CUSTOM_STYLING__inactive              LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "inactive"
#define LV2_DARKGLASS_CUSTOM_STYLING__knob                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "knob"
#define LV2_DARKGLASS_CUSTOM_STYLING__list                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "list"
#define LV2_DARKGLASS_CUSTOM_STYLING__meter                 LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "meter"
#define LV2_DARKGLASS_CUSTOM_STYLING__more                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "more"
#define LV2_DARKGLASS_CUSTOM_STYLING__paginationDots        LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "paginationDots"
#define LV2_DARKGLASS_CUSTOM_STYLING__parameterStartPadding LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "parameterStartPadding"
#define LV2_DARKGLASS_CUSTOM_STYLING__parameters            LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "parameters"
#define LV2_DARKGLASS_CUSTOM_STYLING__path                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "path"
#define LV2_DARKGLASS_CUSTOM_STYLING__remove                LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "remove"
#define LV2_DARKGLASS_CUSTOM_STYLING__size                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "size"
#define LV2_DARKGLASS_CUSTOM_STYLING__swap                  LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "swap"
#define LV2_DARKGLASS_CUSTOM_STYLING__toggle                LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "toggle"
#define LV2_DARKGLASS_CUSTOM_STYLING__topBarButtons         LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "topBarButtons"
#define LV2_DARKGLASS_CUSTOM_STYLING__unavailable           LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "unavailable"
#define LV2_DARKGLASS_CUSTOM_STYLING__width                 LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "width"
#define LV2_DARKGLASS_CUSTOM_STYLING__x                     LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "x"
#define LV2_DARKGLASS_CUSTOM_STYLING__y                     LV2_DARKGLASS_CUSTOM_STYLING_PREFIX "y"

#endif /* LV2_DARKGLASS_CUSTOM_STYLING_H */
